name: build + publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CONTEXT_DIR: './'
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CAPROVER_APP: www
  CAPROVER_SERVER: https://caprover.oleksii-luchnikov.com


jobs:
  build:
    runs-on: ubuntu-latest
    #if: contains(github.event.head_commit.message, 'web')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64 #, linux/arm64 <-- Add for ARM support
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PUBLIC_HELLO=world
            NODE_VERSION=20

      # Uncomment and replace with your server
      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: '${{ env.CAPROVER_SERVER }}'
          app: '${{ env.CAPROVER_APP }}'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/oleksiiluchnikov/oleksii-luchnikov.com:master'
          # image: '${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:master'
